/* global */
// Mock combo data for LoL — keys can be skill (Q/W/E/R), summoner (D/F), or item slots (1-6)

const LOL_CHAMPS = {
  Ahri:    { color: "#C2185B" },
  Yasuo:   { color: "#1565C0" },
  Zed:     { color: "#B71C1C" },
  Lux:     { color: "#B8860B" },
  Riven:   { color: "#5E35B1" },
  Lee:     { color: "#BF6516" },
  Akali:   { color: "#00796B" },
  Jhin:    { color: "#6A1B9A" },
  Vayne:   { color: "#283593" },
  Thresh:  { color: "#2E7D32" },
  Katarina:{ color: "#8B1A1A" },
  Kaisa:   { color: "#4527A0" },
};

// Common LoL active items
const ITEMS = {
  Stopwatch:  { name: "수호 천사 / 시간 왜곡", color: "#E0C97A", icon: "⏱" },
  Hexflash:   { name: "헥스플래시", color: "#3B5998", icon: "✦" },
  Galeforce:  { name: "강풍포", color: "#26A69A", icon: "➤" },
  Shieldbow:  { name: "잠시 후의 활", color: "#7B6F4D", icon: "◓" },
  Hourglass:  { name: "조노의 모래시계", color: "#9E7B2E", icon: "⌛" },
  Botrk:      { name: "굶주린 히드라", color: "#A04848", icon: "✕" },
  Maw:        { name: "마법공학 총검", color: "#7A6BAB", icon: "✶" },
  Ravenous:   { name: "굶주린 자캐", color: "#5C4A2E", icon: "▲" },
};

const COMBOS = [
  {
    id: "1",
    title: "아리 차지 풀콤보 — EQR 매혹 시작",
    author: "FoxSpirit",
    champion: "Ahri",
    difficulty: 2,
    duration: "0:08",
    likes: 2840,
    downloads: 1240,
    views: 18420,
    filename: "ahri_charm_burst.tut",
    timeAgo: "3일 전",
    tags: ["풀콤보", "AP"],
    requirements: { level: "9+", skillHaste: "20+", items: ["루덴의 동반자"] },
    keys: [
      { label: "E", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "R", variant: "ult" },
      { label: "W", variant: "spell" },
      { label: "Q", variant: "spell" },
    ],
  },
  {
    id: "2",
    title: "야스오 점멸 Q3 → R 한타 진입",
    author: "WindShitter",
    champion: "Yasuo",
    difficulty: 3,
    duration: "0:04",
    likes: 5420,
    downloads: 3120,
    views: 42100,
    filename: "yasuo_flash_r.tut",
    timeAgo: "1주 전",
    tags: ["한타", "엔트리"],
    requirements: { level: "6+", skillHaste: "—", items: ["크라켄 학살자"] },
    keys: [
      { label: "Q", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "F", variant: "summoner" },
      { label: "R", variant: "ult" },
    ],
  },
  {
    id: "3",
    title: "제드 W-E-Q + 시간왜곡 풀콤",
    author: "ShadowMain",
    champion: "Zed",
    difficulty: 3,
    duration: "0:06",
    likes: 3920,
    downloads: 2480,
    views: 31200,
    filename: "zed_3shadow.tut",
    timeAgo: "5일 전",
    tags: ["암살", "아이템 활용"],
    requirements: { level: "11+", skillHaste: "25+", items: ["덕블레이드", "수호 천사"] },
    keys: [
      { label: "W", variant: "spell" },
      { label: "E", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "R", variant: "ult" },
      { label: "Q", variant: "spell" },
      { label: "3", item: ITEMS.Stopwatch },
    ],
  },
  {
    id: "4",
    title: "럭스 ER 콤보 — 라인전 포킹용",
    author: "LightBringer",
    champion: "Lux",
    difficulty: 1,
    duration: "0:03",
    likes: 1240,
    downloads: 820,
    views: 9420,
    filename: "lux_poke.tut",
    timeAgo: "2일 전",
    tags: ["라인전", "포크"],
    requirements: { level: "6+", skillHaste: "—", items: ["루덴"] },
    keys: [
      { label: "E", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "R", variant: "ult" },
    ],
  },
  {
    id: "5",
    title: "리븐 Q3 캔슬 → 점멸 R 풀콤",
    author: "SwordKR",
    champion: "Riven",
    difficulty: 3,
    duration: "0:05",
    likes: 6820,
    downloads: 4210,
    views: 58300,
    filename: "riven_animcancel.tut",
    timeAgo: "12시간 전",
    tags: ["캔슬", "점멸"],
    requirements: { level: "11+", skillHaste: "20+", items: ["고통의 프리즘"] },
    keys: [
      { label: "Q", variant: "spell" },
      { label: "A", variant: "default" },
      { label: "Q", variant: "spell" },
      { label: "W", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "F", variant: "summoner" },
      { label: "R", variant: "ult" },
    ],
  },
  {
    id: "6",
    title: "리 신 헥스플래시 인섹킥",
    author: "InsecGod",
    champion: "Lee",
    difficulty: 3,
    duration: "0:07",
    likes: 9210,
    downloads: 5840,
    views: 82100,
    filename: "leesin_insec.tut",
    timeAgo: "2주 전",
    tags: ["갱킹", "인섹"],
    requirements: { level: "6+", skillHaste: "—", items: ["고스트 워커", "헥스플래시"] },
    keys: [
      { label: "Q", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "W", variant: "spell" },
      { label: "D", variant: "summoner" },
      { label: "5", item: ITEMS.Hexflash },
      { label: "R", variant: "ult" },
    ],
  },
  {
    id: "7",
    title: "아칼리 EQR 그림자 어시신",
    author: "InkMage",
    champion: "Akali",
    difficulty: 2,
    duration: "0:04",
    likes: 2120,
    downloads: 1320,
    views: 14820,
    filename: "akali_eqr.tut",
    timeAgo: "4일 전",
    tags: ["암살", "스킬콤보"],
    requirements: { level: "6+", skillHaste: "15+", items: ["헬릭스의 마검"] },
    keys: [
      { label: "E", variant: "spell" },
      { label: "Q", variant: "spell" },
      { label: "R", variant: "ult" },
      { label: "E", variant: "spell" },
    ],
  },
  {
    id: "8",
    title: "케이사 강풍포 + R 진입 콤보",
    author: "VirtuosoGG",
    champion: "Kaisa",
    difficulty: 2,
    duration: "0:05",
    likes: 1820,
    downloads: 920,
    views: 11200,
    filename: "kaisa_galeforce.tut",
    timeAgo: "1주 전",
    tags: ["원거리", "한타"],
    requirements: { level: "9+", skillHaste: "—", items: ["강풍포"] },
    keys: [
      { label: "W", variant: "spell" },
      { label: "E", variant: "spell" },
      { label: "1", item: ITEMS.Galeforce },
      { label: "R", variant: "ult" },
      { label: "A", variant: "default" },
      { label: "Q", variant: "spell" },
    ],
  },
];

COMBOS.forEach((c) => {
  c.championColor = LOL_CHAMPS[c.champion]?.color || "#616161";
  c.authorColor = c.championColor;
});

window.LOL_CHAMPS = LOL_CHAMPS;
window.ITEMS = ITEMS;
window.COMBOS = COMBOS;
