import type { ComboListItemDTO } from "@/lib/api/types";

const PATCH = "16.8.1";

export const MOCK_COMBOS: ComboListItemDTO[] = [
  {
    id: "1",
    title: "Riven Q-AA-Q-AA 풀콤보 (6레벨 이후)",
    author: { id: "u1", nickname: "ComboMaster", avatarUrl: null, riotGameName: null, riotTagLine: null },
    game: { slug: "lol", name: "League of Legends" },
    character: {
      slug: "riven",
      name: "리븐",
      iconUrl: `https://ddragon.leagueoflegends.com/cdn/${PATCH}/img/champion/Riven.png`,
    },
    difficulty: "hard",
    tags: ["풀콤보", "라인전", "6레벨"],
    durationMs: 4500,
    inputSummary: [
      { category: "skill", ref: "RivenQ" },
      { category: "attack" },
      { category: "skill", ref: "RivenQ" },
      { category: "attack_cancel" },
      { category: "skill", ref: "RivenW" },
      { category: "skill", ref: "RivenR" },
    ],
    thumbnailUrl: null,
  videoUrl: null,
    videoCrop: null,
    videoTrim: null,
    likeCount: 89,
    downloadCount: 567,
    viewCount: 1234,
    patchVersion: "16.8",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "2",
    title: "Yasuo E-Q 하리케인 콤보",
    author: { id: "u2", nickname: "RiftKing", avatarUrl: null, riotGameName: null, riotTagLine: null },
    game: { slug: "lol", name: "League of Legends" },
    character: {
      slug: "yasuo",
      name: "야스오",
      iconUrl: `https://ddragon.leagueoflegends.com/cdn/${PATCH}/img/champion/Yasuo.png`,
    },
    difficulty: "medium",
    tags: ["이동기", "다수딜"],
    durationMs: 3200,
    inputSummary: [
      { category: "skill", ref: "YasuoE" },
      { category: "skill", ref: "YasuoQ" },
      { category: "attack" },
      { category: "skill", ref: "YasuoR" },
    ],
    thumbnailUrl: null,
  videoUrl: null,
    videoCrop: null,
    videoTrim: null,
    likeCount: 145,
    downloadCount: 320,
    viewCount: 890,
    patchVersion: "16.8",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "3",
    title: "Zed W-E-Q 섀도우 암살 콤보",
    author: { id: "u3", nickname: "ShadowKing", avatarUrl: null, riotGameName: null, riotTagLine: null },
    game: { slug: "lol", name: "League of Legends" },
    character: {
      slug: "zed",
      name: "제드",
      iconUrl: `https://ddragon.leagueoflegends.com/cdn/${PATCH}/img/champion/Zed.png`,
    },
    difficulty: "hard",
    tags: ["암살", "솔로킬"],
    durationMs: 2800,
    inputSummary: [
      { category: "skill", ref: "ZedW" },
      { category: "skill", ref: "ZedE" },
      { category: "skill", ref: "ZedQ" },
      { category: "summoner_spell", slot: "D", ref: "SummonerFlash" },
      { category: "skill", ref: "ZedR" },
    ],
    thumbnailUrl: null,
  videoUrl: null,
    videoCrop: null,
    videoTrim: null,
    likeCount: 210,
    downloadCount: 980,
    viewCount: 3400,
    patchVersion: "16.8",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "4",
    title: "Ahri E-Q-R 3단 돌진 콤보",
    author: { id: "u4", nickname: "FoxGirl", avatarUrl: null, riotGameName: null, riotTagLine: null },
    game: { slug: "lol", name: "League of Legends" },
    character: {
      slug: "ahri",
      name: "아리",
      iconUrl: `https://ddragon.leagueoflegends.com/cdn/${PATCH}/img/champion/Ahri.png`,
    },
    difficulty: "easy",
    tags: ["기동성", "초보추천"],
    durationMs: 5100,
    inputSummary: [
      { category: "skill", ref: "AhriE" },
      { category: "skill", ref: "AhriQ" },
      { category: "skill", ref: "AhriR" },
      { category: "skill", ref: "AhriR" },
      { category: "skill", ref: "AhriR" },
    ],
    thumbnailUrl: null,
  videoUrl: null,
    videoCrop: null,
    videoTrim: null,
    likeCount: 301,
    downloadCount: 1200,
    viewCount: 5600,
    patchVersion: "16.8",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
  },
  {
    id: "5",
    title: "Lee Sin Q-Q-R 인섹 킥 (고급)",
    author: { id: "u5", nickname: "InSec", avatarUrl: null, riotGameName: null, riotTagLine: null },
    game: { slug: "lol", name: "League of Legends" },
    character: {
      slug: "leesin",
      name: "리 신",
      iconUrl: `https://ddragon.leagueoflegends.com/cdn/${PATCH}/img/champion/LeeSin.png`,
    },
    difficulty: "hard",
    tags: ["인섹킥", "플래쉬", "고급"],
    durationMs: 2100,
    inputSummary: [
      { category: "skill", ref: "LeeSinQ" },
      { category: "skill", ref: "LeeSinQ" },
      { category: "summoner_spell", slot: "D", ref: "SummonerFlash" },
      { category: "skill", ref: "LeeSinR" },
    ],
    thumbnailUrl: null,
  videoUrl: null,
    videoCrop: null,
    videoTrim: null,
    likeCount: 512,
    downloadCount: 2300,
    viewCount: 8900,
    patchVersion: "16.8",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "6",
    title: "Lux EQ 스킬샷 콤보",
    author: { id: "u6", nickname: "LightMage", avatarUrl: null, riotGameName: null, riotTagLine: null },
    game: { slug: "lol", name: "League of Legends" },
    character: {
      slug: "lux",
      name: "럭스",
      iconUrl: `https://ddragon.leagueoflegends.com/cdn/${PATCH}/img/champion/Lux.png`,
    },
    difficulty: "easy",
    tags: ["원거리", "스킬샷", "초보추천"],
    durationMs: 3800,
    inputSummary: [
      { category: "skill", ref: "LuxE" },
      { category: "skill", ref: "LuxQ" },
      { category: "attack" },
      { category: "skill", ref: "LuxR" },
    ],
    thumbnailUrl: null,
  videoUrl: null,
    videoCrop: null,
    videoTrim: null,
    likeCount: 198,
    downloadCount: 760,
    viewCount: 2100,
    patchVersion: "16.8",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];
